### ISSUE TITLE
show metadata even if truncated

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#77] opened 2020-01-26 23:58 UTC
presently if a file is truncated the fmt data is hidden

**Comment by JeromeMartinez** [comment] 2020-04-08 17:02
Isn't it a duplicate of https://github.com/MediaArea/BWFMetaEdit/issues/41?
In my opinion if the request is show & edit (a bit more complicated than show only), please clarify if edit is requested or not.

**Closed** 2020-05-19 15:21 UTC
Labels: enhancement
