### ISSUE TITLE
Does not close multiple files

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#284] opened 2024-03-05 22:02 UTC
- Selecting e.g. three files and then File - > Close 3 Files ... only closes the last one.
- Closing a single file or all files still works

**Comment by g-maxime** [comment] 2024-09-17 09:18
Unable to reproduce this bug with the latest snapshot:  https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240915-2/

Please check

**Comment by JeromeMartinez** [comment] 2024-10-30 10:16
Closing as we can not reproduce.

**Closed** 2024-10-30 10:16 UTC
